modLoader="lowcodefml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]] #mandatory
modId="monocle_locator" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
logoFile="monocle.png" #optional
authors="${mod_authors}" #optional
description='''Locator for Monocle'''
